# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PaddleBall < Formula
  desc "A minimalist physics-based terminal paddleball game with score history"
  homepage "https://paddleball.mvp-subha.me"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.4/paddle-ball_darwin_amd64.tar.gz"
      sha256 "31d6a413b1a20d04be489e41371b72f11b85448923442bc462ec7c166a3798bf"

      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.4/paddle-ball_darwin_arm64.tar.gz"
      sha256 "dcc0e21d9d4a11354763491bf0159bff405e57227c8aeed874911910b8094f1e"

      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.4/paddle-ball_linux_amd64.tar.gz"
      sha256 "5f38ed045376c1a9eaad4856acee2efc8480fe7154084828e90e6c294ad2457d"
      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/subhadeeproy3902/paddle-ball/releases/download/v1.0.4/paddle-ball_linux_arm64.tar.gz"
      sha256 "fc50345f937f6961265ed5a519195e786b61f3d7aa7dea26849e9093d3c76186"
      define_method(:install) do
        bin.install "paddle-ball"
      end
    end
  end

  test do
    system "#{bin}/paddle-ball version"
  end
end
